name: java-code-style-check
author: "Rufet Mezemov"
description: "Java code style check"
inputs:
  java-distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"
  java-version:
    description: "Java version to use"
    required: false
    default: "17"
  cache:
    description: "Build tool caching"
    required: false
    default: "true"
  gradle-version:
    description: "Gradle version"
    required: false
    default: "wrapper"
runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle and run Checkstyle task
      uses: gradle/gradle-build-action@v2
      env:
        GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: ${{ inputs.cache }}
      with:
        gradle-version: ${{ inputs.gradle-version }}
        arguments: checkstyleMain