name: go-build
author: 'Pərvin Yaqubzadə'
description: 'GitHub action for sending test test coverage report to SonarCloud for Go projects'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.19'
  github-token:
    description: 'GitHub token for authorization'
    required: true
  sonar-login:
    description: 'SonarCloud token for authorization'
    required: true
  sonar-organization:
    description: 'Organization key in SonarCloud'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Test
      run: |
        go mod download
        go test ./... -v -coverprofile cover.out
      shell: bash

    - name: Send coverage report to SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-login }}
      with:
        args: >
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.organization=${{ inputs.sonar-organization }}
          -Dsonar.projectName=${{ github.event.repository.name }}
          -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}