name: go-build
author: 'Pərvin Yaqubzadə'
description: 'Build Go project'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.19'
  build-only:
    description: 'Run only build'
    required: false
    default: 'false'
  test-only:
    description: 'Run only test'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: -E revive

    - name: Vet
      run: |
        pwd
        if [[ ${{ inputs.build-only }} != true ]] && [[ ${{ inputs.test-only }} != true ]]
        then
          go vet ./...
        fi
      shell: bash

    - name: Test
      run: |
        pwd
        if [[ ${{ inputs.build-only }} != true ]]
        then
          go mod download
          go test ./... -v
        fi
      shell: bash

    - name: Build
      run: |
        pwd
        if [[ ${{ inputs.test-only }} != true ]]
        then
          go mod download
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a
        fi
      shell: bash