name: send-to-sonar
author: "Rufet Mezemov"
description: "Send to Sonar"
inputs:
  java-distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"
  java-version:
    description: "Java version to use"
    required: false
    default: "17"
  cache:
    description: "Build tool caching"
    required: false
    default: "true"
  gradle-version:
    description: "Gradle version"
    required: false
    default: "wrapper"
  github-token:
    description: "GITHUB_TOKEN"
    required: true
    default: "secrets.GITHUB_TOKEN"
  sonar-token:
    description: "SONAR_TOKEN"
    required: true
    default: "secrets.SONAR_TOKEN"
runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Send to SonarCloud
      uses: gradle/gradle-build-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: ${{ inputs.cache }}
      with:
        gradle-version: ${{ inputs.gradle-version }}
        arguments: sonarqube